version: "2"
services:
  server:
    build:
      context: .
    volumes:
      - ./:/server
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
