
FROM node:dubnium-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
RUN mkdir /server
WORKDIR /server

COPY package.json /server
RUN npm install 

COPY . /server

CMD /wait && npm run test